<a href="https://colab.research.google.com/github/javeed141/Bank-Churn-Prediction/blob/main/PyTorch_Baisc_Operations_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
import torch
print(torch.__version__)


2.9.0+cu126


In [6]:
import torch
if(torch.cuda.is_available()):
  print(torch.cuda.get_device_name(0))


Tesla T4


# Creating a Tensor

In [7]:
torch.empty(2,3)

tensor([[4.5447e+30, 3.0750e+29, 1.9284e+31],
        [1.8891e+31, 8.3195e+35, 2.1708e-18]])

In [9]:
a=torch.empty(2,3)

In [10]:
type(a)

torch.Tensor

In [12]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [15]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch.rand(2,3)

tensor([[0.9211, 0.4784, 0.1890],
        [0.0023, 0.2714, 0.9085]])

In [17]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [19]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.linspace(1,10,5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [23]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [24]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [25]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [26]:
x.shape

torch.Size([2, 3])

In [27]:
torch.empty_like(x)

tensor([[807225984, 807061328,         0],
        [        0,         0,         0]])

In [28]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [29]:
x.dtype

torch.int64

In [30]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [35]:
x.to()

tensor([[1, 2, 3],
        [4, 5, 6]])

SyntaxError: invalid syntax (ipython-input-2663880562.py, line 1)

In [36]:
x=torch.tensor([[1.4,2.7,3.5],[4,5,6]])

In [37]:
e=torch.clamp(x,min=2,max=3)

In [38]:
e

tensor([[2.0000, 2.7000, 3.0000],
        [3.0000, 3.0000, 3.0000]])

In [39]:
a=torch.randint(size=(2,3),low=0,high=10)

In [40]:
a

tensor([[2, 8, 8],
        [0, 4, 3]])

In [46]:
b=torch.tensor([[1,2,3,6],[4,5,6,4],[7,8,9,14],[10,11,12,54]],dtype=torch.float64)
b.shape

torch.Size([4, 4])

In [47]:
re=b.reshape(2,2,2,2)

In [48]:
re

tensor([[[[ 1.,  2.],
          [ 3.,  6.]],

         [[ 4.,  5.],
          [ 6.,  4.]]],


        [[[ 7.,  8.],
          [ 9., 14.]],

         [[10., 11.],
          [12., 54.]]]], dtype=torch.float64)

In [49]:
b.flatten()

tensor([ 1.,  2.,  3.,  6.,  4.,  5.,  6.,  4.,  7.,  8.,  9., 14., 10., 11.,
        12., 54.], dtype=torch.float64)

In [50]:
import torch

x = torch.tensor([1, 2, 3])
print(x.shape)
y = x.unsqueeze(0)
print(y.shape)


torch.Size([3])
torch.Size([1, 3])


In [51]:
y

tensor([[1, 2, 3]])

In [52]:
z = x.unsqueeze(1)
print(z.shape)


torch.Size([3, 1])


In [53]:
z

tensor([[1],
        [2],
        [3]])

In [54]:
y = x.squeeze()
print(y.shape)


torch.Size([3])


In [55]:
y

tensor([1, 2, 3])